### ISSUE TITLE
FPS Counter And Clock Not Showing Up

### ISSUE THREAD

**Issue by MidgeThePidge** [44670/ntr_overlay_samples#1]
Title says it all. I feel like I'm not putting the things in the right folders though.

**Comment by 44670** [comment]
Which title are you trying on? Is blue-light reduction workable in that title?

**Comment by MidgeThePidge** [comment]
I finally fixed the issue. I was on 3.4 Preview 2 which I think didn't support overlay plugins. I got preview 4 and everything is working fine!
