### ISSUE TITLE
Any chance for "global plugins"?

### ISSUE THREAD

**Issue by vaguerant** [44670/ntr_overlay_samples#2]
It's been fun trying out the framerate and clock plugins in NTR, but keeping and managing many copies in separate title ID folders seems inefficient. Perhaps it could be possible to drop plugins directly into the plugin directory, with an in-menu toggle for whether they should be run or not?

**Comment by 44670** [comment]
copy the .plg file in to '/plugin/game' and it will be loaded for any games

**Comment by vaguerant** [comment]
Ah! Thank you, sorry for not noticing that myself.
